name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-virtualenv adb git
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer==1.5.0

    - name: Initialize Buildozer
      run: |
        buildozer android clean
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: built-apk
        path: bin/*.apk
