name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-virtualenv adb wget
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK & accept licenses
      run: |
        mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        chmod +x $HOME/android-sdk/cmdline-tools/latest/bin/*
        export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin
        yes | sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;25.2.9519653"
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: built-apk
        path: bin/*.apk
