name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-virtualenv adb
        pip install --upgrade pip
        pip install buildozer cython

    - name: Set up Android SDK environment
      run: |
        mkdir -p $HOME/android-sdk
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip sdk-tools.zip -d $ANDROID_SDK_ROOT
        yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses || true
        # SDK প্ল্যাটফর্ম ও বিল্ড-টুলস ইনস্টল করুন
        $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-33" "build-tools;33.0.0" "platform-tools"

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: built-apk
        path: bin/*.apk
